// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL_ulK2kjc1EyVSEAMnSFi6EH_pxn4MJs',
    appId: '1:328496191094:web:53b1eb05ddcdf96776b157',
    messagingSenderId: '328496191094',
    projectId: 'clone-sea-talk-baru',
    authDomain: 'clone-sea-talk-baru.firebaseapp.com',
    storageBucket: 'clone-sea-talk-baru.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1LYBrVW07JbWA7nv58JdLMUEHhSfsuho',
    appId: '1:328496191094:android:d97dc8dd0f21473276b157',
    messagingSenderId: '328496191094',
    projectId: 'clone-sea-talk-baru',
    storageBucket: 'clone-sea-talk-baru.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBOiF_9G-rnJtI7Z6BMsK2FtcEBXcSZ3Q',
    appId: '1:328496191094:ios:b30e8c21399c6abc76b157',
    messagingSenderId: '328496191094',
    projectId: 'clone-sea-talk-baru',
    storageBucket: 'clone-sea-talk-baru.appspot.com',
    androidClientId: '328496191094-p0c5hd51uqi10d0r1m6ibobhm8g0l808.apps.googleusercontent.com',
    iosClientId: '328496191094-o7icmtcj4tacsfoocv7inul1elma6kkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.todos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBOiF_9G-rnJtI7Z6BMsK2FtcEBXcSZ3Q',
    appId: '1:328496191094:ios:965317ca624c71e376b157',
    messagingSenderId: '328496191094',
    projectId: 'clone-sea-talk-baru',
    storageBucket: 'clone-sea-talk-baru.appspot.com',
    androidClientId: '328496191094-p0c5hd51uqi10d0r1m6ibobhm8g0l808.apps.googleusercontent.com',
    iosClientId: '328496191094-oi5dsavfov5d9rfqq49gnfbfldvo6miv.apps.googleusercontent.com',
    iosBundleId: 'com.example.todos.RunnerTests',
  );
}
